//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("LifeTubeModel", "FK_Users_Profile", "Profile", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(LifeTube.Models.Profile), "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LifeTube.Models.User), true)]
[assembly: EdmRelationshipAttribute("LifeTubeModel", "FK_UserCircles_Users", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(LifeTube.Models.User), "UserCircles", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LifeTube.Models.UserCircle), true)]
[assembly: EdmRelationshipAttribute("LifeTubeModel", "FK_UserCircles_Users1", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(LifeTube.Models.User), "UserCircles", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LifeTube.Models.UserCircle), true)]

#endregion

namespace LifeTube.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class LifeTubeEntities1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new LifeTubeEntities1 object using the connection string found in the 'LifeTubeEntities1' section of the application configuration file.
        /// </summary>
        public LifeTubeEntities1() : base("name=LifeTubeEntities1", "LifeTubeEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LifeTubeEntities1 object.
        /// </summary>
        public LifeTubeEntities1(string connectionString) : base(connectionString, "LifeTubeEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LifeTubeEntities1 object.
        /// </summary>
        public LifeTubeEntities1(EntityConnection connection) : base(connection, "LifeTubeEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Profile> Profiles
        {
            get
            {
                if ((_Profiles == null))
                {
                    _Profiles = base.CreateObjectSet<Profile>("Profiles");
                }
                return _Profiles;
            }
        }
        private ObjectSet<Profile> _Profiles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UserCircle> UserCircles
        {
            get
            {
                if ((_UserCircles == null))
                {
                    _UserCircles = base.CreateObjectSet<UserCircle>("UserCircles");
                }
                return _UserCircles;
            }
        }
        private ObjectSet<UserCircle> _UserCircles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Profiles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProfiles(Profile profile)
        {
            base.AddObject("Profiles", profile);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UserCircles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUserCircles(UserCircle userCircle)
        {
            base.AddObject("UserCircles", userCircle);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LifeTubeModel", Name="Profile")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Profile : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Profile object.
        /// </summary>
        /// <param name="profileId">Initial value of the profileId property.</param>
        public static Profile CreateProfile(global::System.Int32 profileId)
        {
            Profile profile = new Profile();
            profile.profileId = profileId;
            return profile;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 profileId
        {
            get
            {
                return _profileId;
            }
            set
            {
                if (_profileId != value)
                {
                    OnprofileIdChanging(value);
                    ReportPropertyChanging("profileId");
                    _profileId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("profileId");
                    OnprofileIdChanged();
                }
            }
        }
        private global::System.Int32 _profileId;
        partial void OnprofileIdChanging(global::System.Int32 value);
        partial void OnprofileIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String profileName
        {
            get
            {
                return _profileName;
            }
            set
            {
                OnprofileNameChanging(value);
                ReportPropertyChanging("profileName");
                _profileName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("profileName");
                OnprofileNameChanged();
            }
        }
        private global::System.String _profileName;
        partial void OnprofileNameChanging(global::System.String value);
        partial void OnprofileNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String firstName
        {
            get
            {
                return _firstName;
            }
            set
            {
                OnfirstNameChanging(value);
                ReportPropertyChanging("firstName");
                _firstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("firstName");
                OnfirstNameChanged();
            }
        }
        private global::System.String _firstName;
        partial void OnfirstNameChanging(global::System.String value);
        partial void OnfirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String lastName
        {
            get
            {
                return _lastName;
            }
            set
            {
                OnlastNameChanging(value);
                ReportPropertyChanging("lastName");
                _lastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("lastName");
                OnlastNameChanged();
            }
        }
        private global::System.String _lastName;
        partial void OnlastNameChanging(global::System.String value);
        partial void OnlastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> dateOfBirth
        {
            get
            {
                return _dateOfBirth;
            }
            set
            {
                OndateOfBirthChanging(value);
                ReportPropertyChanging("dateOfBirth");
                _dateOfBirth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dateOfBirth");
                OndateOfBirthChanged();
            }
        }
        private Nullable<global::System.DateTime> _dateOfBirth;
        partial void OndateOfBirthChanging(Nullable<global::System.DateTime> value);
        partial void OndateOfBirthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String streetAddress
        {
            get
            {
                return _streetAddress;
            }
            set
            {
                OnstreetAddressChanging(value);
                ReportPropertyChanging("streetAddress");
                _streetAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("streetAddress");
                OnstreetAddressChanged();
            }
        }
        private global::System.String _streetAddress;
        partial void OnstreetAddressChanging(global::System.String value);
        partial void OnstreetAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String city
        {
            get
            {
                return _city;
            }
            set
            {
                OncityChanging(value);
                ReportPropertyChanging("city");
                _city = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("city");
                OncityChanged();
            }
        }
        private global::System.String _city;
        partial void OncityChanging(global::System.String value);
        partial void OncityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String postalCode
        {
            get
            {
                return _postalCode;
            }
            set
            {
                OnpostalCodeChanging(value);
                ReportPropertyChanging("postalCode");
                _postalCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("postalCode");
                OnpostalCodeChanged();
            }
        }
        private global::System.String _postalCode;
        partial void OnpostalCodeChanging(global::System.String value);
        partial void OnpostalCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String country
        {
            get
            {
                return _country;
            }
            set
            {
                OncountryChanging(value);
                ReportPropertyChanging("country");
                _country = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("country");
                OncountryChanged();
            }
        }
        private global::System.String _country;
        partial void OncountryChanging(global::System.String value);
        partial void OncountryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String gender
        {
            get
            {
                return _gender;
            }
            set
            {
                OngenderChanging(value);
                ReportPropertyChanging("gender");
                _gender = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("gender");
                OngenderChanged();
            }
        }
        private global::System.String _gender;
        partial void OngenderChanging(global::System.String value);
        partial void OngenderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String religion
        {
            get
            {
                return _religion;
            }
            set
            {
                OnreligionChanging(value);
                ReportPropertyChanging("religion");
                _religion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("religion");
                OnreligionChanged();
            }
        }
        private global::System.String _religion;
        partial void OnreligionChanging(global::System.String value);
        partial void OnreligionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String homeTown
        {
            get
            {
                return _homeTown;
            }
            set
            {
                OnhomeTownChanging(value);
                ReportPropertyChanging("homeTown");
                _homeTown = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("homeTown");
                OnhomeTownChanged();
            }
        }
        private global::System.String _homeTown;
        partial void OnhomeTownChanging(global::System.String value);
        partial void OnhomeTownChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String studiedAt
        {
            get
            {
                return _studiedAt;
            }
            set
            {
                OnstudiedAtChanging(value);
                ReportPropertyChanging("studiedAt");
                _studiedAt = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("studiedAt");
                OnstudiedAtChanged();
            }
        }
        private global::System.String _studiedAt;
        partial void OnstudiedAtChanging(global::System.String value);
        partial void OnstudiedAtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String workAt
        {
            get
            {
                return _workAt;
            }
            set
            {
                OnworkAtChanging(value);
                ReportPropertyChanging("workAt");
                _workAt = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("workAt");
                OnworkAtChanged();
            }
        }
        private global::System.String _workAt;
        partial void OnworkAtChanging(global::System.String value);
        partial void OnworkAtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> createdOn
        {
            get
            {
                return _createdOn;
            }
            set
            {
                OncreatedOnChanging(value);
                ReportPropertyChanging("createdOn");
                _createdOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createdOn");
                OncreatedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _createdOn;
        partial void OncreatedOnChanging(Nullable<global::System.DateTime> value);
        partial void OncreatedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String personalContect
        {
            get
            {
                return _personalContect;
            }
            set
            {
                OnpersonalContectChanging(value);
                ReportPropertyChanging("personalContect");
                _personalContect = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("personalContect");
                OnpersonalContectChanged();
            }
        }
        private global::System.String _personalContect;
        partial void OnpersonalContectChanging(global::System.String value);
        partial void OnpersonalContectChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String homeContact
        {
            get
            {
                return _homeContact;
            }
            set
            {
                OnhomeContactChanging(value);
                ReportPropertyChanging("homeContact");
                _homeContact = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("homeContact");
                OnhomeContactChanged();
            }
        }
        private global::System.String _homeContact;
        partial void OnhomeContactChanging(global::System.String value);
        partial void OnhomeContactChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String bloodGroup
        {
            get
            {
                return _bloodGroup;
            }
            set
            {
                OnbloodGroupChanging(value);
                ReportPropertyChanging("bloodGroup");
                _bloodGroup = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("bloodGroup");
                OnbloodGroupChanged();
            }
        }
        private global::System.String _bloodGroup;
        partial void OnbloodGroupChanging(global::System.String value);
        partial void OnbloodGroupChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String birthPlace
        {
            get
            {
                return _birthPlace;
            }
            set
            {
                OnbirthPlaceChanging(value);
                ReportPropertyChanging("birthPlace");
                _birthPlace = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("birthPlace");
                OnbirthPlaceChanged();
            }
        }
        private global::System.String _birthPlace;
        partial void OnbirthPlaceChanging(global::System.String value);
        partial void OnbirthPlaceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String hobby
        {
            get
            {
                return _hobby;
            }
            set
            {
                OnhobbyChanging(value);
                ReportPropertyChanging("hobby");
                _hobby = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("hobby");
                OnhobbyChanged();
            }
        }
        private global::System.String _hobby;
        partial void OnhobbyChanging(global::System.String value);
        partial void OnhobbyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> lastModifiedOn
        {
            get
            {
                return _lastModifiedOn;
            }
            set
            {
                OnlastModifiedOnChanging(value);
                ReportPropertyChanging("lastModifiedOn");
                _lastModifiedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("lastModifiedOn");
                OnlastModifiedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _lastModifiedOn;
        partial void OnlastModifiedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnlastModifiedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] profilePicture
        {
            get
            {
                return StructuralObject.GetValidValue(_profilePicture);
            }
            set
            {
                OnprofilePictureChanging(value);
                ReportPropertyChanging("profilePicture");
                _profilePicture = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("profilePicture");
                OnprofilePictureChanged();
            }
        }
        private global::System.Byte[] _profilePicture;
        partial void OnprofilePictureChanging(global::System.Byte[] value);
        partial void OnprofilePictureChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LifeTubeModel", "FK_Users_Profile", "Users")]
        public EntityCollection<User> Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<User>("LifeTubeModel.FK_Users_Profile", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<User>("LifeTubeModel.FK_Users_Profile", "Users", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LifeTubeModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="userid">Initial value of the userid property.</param>
        public static User CreateUser(global::System.Int32 userid)
        {
            User user = new User();
            user.userid = userid;
            return user;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 userid
        {
            get
            {
                return _userid;
            }
            set
            {
                if (_userid != value)
                {
                    OnuseridChanging(value);
                    ReportPropertyChanging("userid");
                    _userid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("userid");
                    OnuseridChanged();
                }
            }
        }
        private global::System.Int32 _userid;
        partial void OnuseridChanging(global::System.Int32 value);
        partial void OnuseridChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String firstName
        {
            get
            {
                return _firstName;
            }
            set
            {
                OnfirstNameChanging(value);
                ReportPropertyChanging("firstName");
                _firstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("firstName");
                OnfirstNameChanged();
            }
        }
        private global::System.String _firstName;
        partial void OnfirstNameChanging(global::System.String value);
        partial void OnfirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String lastName
        {
            get
            {
                return _lastName;
            }
            set
            {
                OnlastNameChanging(value);
                ReportPropertyChanging("lastName");
                _lastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("lastName");
                OnlastNameChanged();
            }
        }
        private global::System.String _lastName;
        partial void OnlastNameChanging(global::System.String value);
        partial void OnlastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> profileId
        {
            get
            {
                return _profileId;
            }
            set
            {
                OnprofileIdChanging(value);
                ReportPropertyChanging("profileId");
                _profileId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("profileId");
                OnprofileIdChanged();
            }
        }
        private Nullable<global::System.Int32> _profileId;
        partial void OnprofileIdChanging(Nullable<global::System.Int32> value);
        partial void OnprofileIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String phone
        {
            get
            {
                return _phone;
            }
            set
            {
                OnphoneChanging(value);
                ReportPropertyChanging("phone");
                _phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("phone");
                OnphoneChanged();
            }
        }
        private global::System.String _phone;
        partial void OnphoneChanging(global::System.String value);
        partial void OnphoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> createdBy
        {
            get
            {
                return _createdBy;
            }
            set
            {
                OncreatedByChanging(value);
                ReportPropertyChanging("createdBy");
                _createdBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createdBy");
                OncreatedByChanged();
            }
        }
        private Nullable<global::System.Int32> _createdBy;
        partial void OncreatedByChanging(Nullable<global::System.Int32> value);
        partial void OncreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> createdDate
        {
            get
            {
                return _createdDate;
            }
            set
            {
                OncreatedDateChanging(value);
                ReportPropertyChanging("createdDate");
                _createdDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createdDate");
                OncreatedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _createdDate;
        partial void OncreatedDateChanging(Nullable<global::System.DateTime> value);
        partial void OncreatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> lastModifiedBy
        {
            get
            {
                return _lastModifiedBy;
            }
            set
            {
                OnlastModifiedByChanging(value);
                ReportPropertyChanging("lastModifiedBy");
                _lastModifiedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("lastModifiedBy");
                OnlastModifiedByChanged();
            }
        }
        private Nullable<global::System.Int32> _lastModifiedBy;
        partial void OnlastModifiedByChanging(Nullable<global::System.Int32> value);
        partial void OnlastModifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> lastModifiedDate
        {
            get
            {
                return _lastModifiedDate;
            }
            set
            {
                OnlastModifiedDateChanging(value);
                ReportPropertyChanging("lastModifiedDate");
                _lastModifiedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("lastModifiedDate");
                OnlastModifiedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _lastModifiedDate;
        partial void OnlastModifiedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnlastModifiedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> rootUser
        {
            get
            {
                return _rootUser;
            }
            set
            {
                OnrootUserChanging(value);
                ReportPropertyChanging("rootUser");
                _rootUser = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rootUser");
                OnrootUserChanged();
            }
        }
        private Nullable<global::System.Boolean> _rootUser;
        partial void OnrootUserChanging(Nullable<global::System.Boolean> value);
        partial void OnrootUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String resetPin
        {
            get
            {
                return _resetPin;
            }
            set
            {
                OnresetPinChanging(value);
                ReportPropertyChanging("resetPin");
                _resetPin = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("resetPin");
                OnresetPinChanged();
            }
        }
        private global::System.String _resetPin;
        partial void OnresetPinChanging(global::System.String value);
        partial void OnresetPinChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LifeTubeModel", "FK_Users_Profile", "Profile")]
        public Profile Profile
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Profile>("LifeTubeModel.FK_Users_Profile", "Profile").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Profile>("LifeTubeModel.FK_Users_Profile", "Profile").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Profile> ProfileReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Profile>("LifeTubeModel.FK_Users_Profile", "Profile");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Profile>("LifeTubeModel.FK_Users_Profile", "Profile", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LifeTubeModel", "FK_UserCircles_Users", "UserCircles")]
        public EntityCollection<UserCircle> UserCircles
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UserCircle>("LifeTubeModel.FK_UserCircles_Users", "UserCircles");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UserCircle>("LifeTubeModel.FK_UserCircles_Users", "UserCircles", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LifeTubeModel", "FK_UserCircles_Users1", "UserCircles")]
        public EntityCollection<UserCircle> UserCircles1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UserCircle>("LifeTubeModel.FK_UserCircles_Users1", "UserCircles");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UserCircle>("LifeTubeModel.FK_UserCircles_Users1", "UserCircles", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LifeTubeModel", Name="UserCircle")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserCircle : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UserCircle object.
        /// </summary>
        /// <param name="userCircleId">Initial value of the userCircleId property.</param>
        public static UserCircle CreateUserCircle(global::System.Int32 userCircleId)
        {
            UserCircle userCircle = new UserCircle();
            userCircle.userCircleId = userCircleId;
            return userCircle;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 userCircleId
        {
            get
            {
                return _userCircleId;
            }
            set
            {
                if (_userCircleId != value)
                {
                    OnuserCircleIdChanging(value);
                    ReportPropertyChanging("userCircleId");
                    _userCircleId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("userCircleId");
                    OnuserCircleIdChanged();
                }
            }
        }
        private global::System.Int32 _userCircleId;
        partial void OnuserCircleIdChanging(global::System.Int32 value);
        partial void OnuserCircleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> userFrom
        {
            get
            {
                return _userFrom;
            }
            set
            {
                OnuserFromChanging(value);
                ReportPropertyChanging("userFrom");
                _userFrom = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("userFrom");
                OnuserFromChanged();
            }
        }
        private Nullable<global::System.Int32> _userFrom;
        partial void OnuserFromChanging(Nullable<global::System.Int32> value);
        partial void OnuserFromChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> userTo
        {
            get
            {
                return _userTo;
            }
            set
            {
                OnuserToChanging(value);
                ReportPropertyChanging("userTo");
                _userTo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("userTo");
                OnuserToChanged();
            }
        }
        private Nullable<global::System.Int32> _userTo;
        partial void OnuserToChanging(Nullable<global::System.Int32> value);
        partial void OnuserToChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String relationship
        {
            get
            {
                return _relationship;
            }
            set
            {
                OnrelationshipChanging(value);
                ReportPropertyChanging("relationship");
                _relationship = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("relationship");
                OnrelationshipChanged();
            }
        }
        private global::System.String _relationship;
        partial void OnrelationshipChanging(global::System.String value);
        partial void OnrelationshipChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> createdBy
        {
            get
            {
                return _createdBy;
            }
            set
            {
                OncreatedByChanging(value);
                ReportPropertyChanging("createdBy");
                _createdBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createdBy");
                OncreatedByChanged();
            }
        }
        private Nullable<global::System.Int32> _createdBy;
        partial void OncreatedByChanging(Nullable<global::System.Int32> value);
        partial void OncreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> createdOn
        {
            get
            {
                return _createdOn;
            }
            set
            {
                OncreatedOnChanging(value);
                ReportPropertyChanging("createdOn");
                _createdOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createdOn");
                OncreatedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _createdOn;
        partial void OncreatedOnChanging(Nullable<global::System.DateTime> value);
        partial void OncreatedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> lastModifiedBy
        {
            get
            {
                return _lastModifiedBy;
            }
            set
            {
                OnlastModifiedByChanging(value);
                ReportPropertyChanging("lastModifiedBy");
                _lastModifiedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("lastModifiedBy");
                OnlastModifiedByChanged();
            }
        }
        private Nullable<global::System.Int32> _lastModifiedBy;
        partial void OnlastModifiedByChanging(Nullable<global::System.Int32> value);
        partial void OnlastModifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> lastModifiedDate
        {
            get
            {
                return _lastModifiedDate;
            }
            set
            {
                OnlastModifiedDateChanging(value);
                ReportPropertyChanging("lastModifiedDate");
                _lastModifiedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("lastModifiedDate");
                OnlastModifiedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _lastModifiedDate;
        partial void OnlastModifiedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnlastModifiedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> isAccepted
        {
            get
            {
                return _isAccepted;
            }
            set
            {
                OnisAcceptedChanging(value);
                ReportPropertyChanging("isAccepted");
                _isAccepted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isAccepted");
                OnisAcceptedChanged();
            }
        }
        private Nullable<global::System.Boolean> _isAccepted;
        partial void OnisAcceptedChanging(Nullable<global::System.Boolean> value);
        partial void OnisAcceptedChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LifeTubeModel", "FK_UserCircles_Users", "Users")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("LifeTubeModel.FK_UserCircles_Users", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("LifeTubeModel.FK_UserCircles_Users", "Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("LifeTubeModel.FK_UserCircles_Users", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("LifeTubeModel.FK_UserCircles_Users", "Users", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LifeTubeModel", "FK_UserCircles_Users1", "Users")]
        public User User1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("LifeTubeModel.FK_UserCircles_Users1", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("LifeTubeModel.FK_UserCircles_Users1", "Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> User1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("LifeTubeModel.FK_UserCircles_Users1", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("LifeTubeModel.FK_UserCircles_Users1", "Users", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
